### ISSUE TITLE
NULL-byte in exported Tab file

### ISSUE THREAD

**Issue by kernc** [amcat/orange3sma#1]
When exporting data from Facebook, the resulting Tab file sometimes contains a NULL-byte that can't be interpreted when later importing. Either that, or some encoding is off.

Original issue: https://github.com/biolab/orange3/issues/2967

**Comment by kasperwelbers** [comment]
Sorry for not noticing this issue sooner. Coincidentally, a student noticed this as well, so we fixed it some time ago (by simply removing NULL-byte from FB output). The updated version should already be on pip, so please let me know if it still occurs, because then we're missing something.
